apiVersion: apps/v1
kind: Deployment
metadata:
  name: learningsteps-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learningsteps-app
  template:
    metadata:
      labels:
        app: learningsteps-app
    spec: 
      containers: 
      - name: app-container
        image: learningstepsreg01.azurecr.io/learningsteps-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: learningsteps-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: learningsteps-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: learningsteps-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: learningsteps-config
              key: DB_USER
        # Temporarily leaving the sensitive password here until we link Azure Key Vault next!
        - name: DB_PASSWORD
          value: "YourSecurePassword"