apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: learningsteps-kv-provider
  namespace: default
spec:
  provider: azure
  parameters:
    useManagedIdentity: "true"
    userAssignedIdentityID: "" # Keeping this blank forces it to fall back to system Kubelet identity automatically
    keyvaultName: "learningsteps-kv-hpkl4f"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""
    tenantId: "e6744405-892d-4ea5-987a-cfe11463a4dc" # implicit Azure directory identifier
  # Automatically syncs the mounted vault secret into a standard Kubernetes Secret token mapping
  secretObjects:
  - secretName: learningsteps-app-secret
    type: Opaque
    data:
    - objectName: db-password
      key: DB_PASSWORD