apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: learningsteps-kv-provider
  namespace: default
spec:
  provider: azure
  # ========================================================================
  # SUCCESS CONFIGURATION: Locked Casing Key Structure
  # ========================================================================
  parameters:
    useVMManagedIdentity: "true"                      # ◄ Explicitly utilize Azure Managed Identity
    userAssignedIdentityID: "a3ff2b26-9877-457e-98d8-5b6e2ebbd413" # ◄ Capital ID structure
    keyVaultName: "learningsteps-kv-76fgv4"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""
    tenantId: "e6744405-892d-4ea5-987a-cfe11463a4dc"
  # Automatically syncs the mounted vault secret into a standard Kubernetes Secret token mapping
  secretObjects:
  - secretName: learningsteps-app-secret
    type: Opaque
    data:
    - objectName: db-password
      key: DB_PASSWORD